services:
  sales.api:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: src/Sales.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__Default: >
        Server=sqlserver;
        Database=Sales;
        User Id=sa;
        Password=${SA_PASSWORD};
        Encrypt=True;
        TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    # restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: